### ISSUE TITLE
可以增加个输出结果json格式吗，方便集成其他程序。

### ISSUE THREAD

**Issue by sharemice** [ShiHuang-ESec/EHole#12]
可以增加个输出结果json格式吗，方便集成其他程序，单纯的日志处理比较麻烦

**Comment by ShiHuang-ESec** [comment]
可以，但是估计要过几天

**Comment by possib1e** [comment]
是啊，尤其是重点资产和普通资产日志里面的格式还不一样，重点资产多了一个字段，很不方便进一步提取，辛苦作者了。

**Comment by ShiHuang-ESec** [comment]
EHole 2.0发布了，指纹开源了，支持json输出，本项目地址不再更新，项目地址移至：https : //github.com/EdgeSecurityTeam/EHole
