### ISSUE TITLE
大佬有bug

### ISSUE THREAD

**Issue by whizsail** [ShiHuang-ESec/EHole#7]
2020/12/09 10:23:58 Unable to make request:  Get "https://fofa.so/api/v1/search/all?email=+++++++++++++&page=1&size=100&key=++++++++++++&qbase64=++++++++++++++++": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

命令是 -f 和一个c端

**Comment by ShiHuang-ESec** [comment]
你的本机设置了代理，或者你的网络不通fofa

**Comment by dogadmin** [comment]
你好，我也是出现了这个问题，我在本机以及云服务器都测试了，fofa能直接访问，但是依旧是timeout现象。

**Comment by dogadmin** [comment]
我刚才看了一下 应该是给到fofa接口的timeout时间有点少，是否可以提供部分自定义参数，例如线程、超时时间等

**Comment by Pretexts** [comment]
昨天还是可以的，今天都出现了这个问题，可能是fofa那边改了超时时间？麻烦大佬测试一下。

**Comment by ShiHuang-ESec** [comment]
您的建议我们已经收到，我们会尽快更新

**Comment by ShiHuang-ESec** [comment]
已更新，新增-ftime参数，设置fofa超时
